//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autoecoleEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicule
    {
        public string numImma { get; set; }
        public string modele { get; set; }
        public string couleur { get; set; }
        public short enEtat { get; set; }
    }
}
